name: "compile-themes"
description: "Compile the .scss theme files into .css files in the build directory"

runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install npm dependencies
        run: |
            npm ci
            npm install -g sass
        shell: bash

      - name: compile chimera themes
        run: |
          sass src/themes/chimera.scss build/chimera.css
          sass src/themes/chimera-dark.scss build/chimera-dark.css
          sass src/themes/chimera-golden.scss build/chimera-golden.css
          sass src/themes/chimera-autumn.scss build/chimera-autumn.css
          sass src/themes/chimera-plain.scss build/chimera-plain.css
        shell: bash
