# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  format-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npx prettier . --write

  compile-sass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: install sass dependency
        run: npm install -g sass
      - name: compile chimera theme
        run: sass sass/chimera.scss css/chimera.css
      - name: compile chimera-dark theme
        run: sass sass/chimera-dark.scss css/chimera-dark.css
      - name: compile chimera-golden theme
        run: sass sass/chimera-golden.scss css/chimera-golden.css

  publish-npm:
    needs: [format-prettier, compile-sass]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Set Git user name and email
        run: |
          git config --global user.email "markusarj@gmail.com"
          git config --global user.name "J0hans1"
      - name: Set package version
        run: npm version ${{ github.event.release.tag_name }}
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
