
on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'SECURITY.md'
            - 'LICENCE'
            - 'GUIDE.md'
            - 'CONTRIBUTING.md'
            - 'CODE_OF_CONDUCT.md'

jobs:
    compile-themes:
        runs-on: ubuntu-latest
        name: compile themes
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: compile sass
          uses: ./.github/actions/compile-themes
