name: PR
on:
    pull_request:
        branches:
            - main
jobs:
    compile-themes:
        runs-on: ubuntu-latest
        name: compile themes
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: compile sass
          uses: ./.github/actions/compile-themes
    axe:
        runs-on: ubuntu-latest
        name: checking accessibility
        steps: 
          - uses: actions/checkout@v2
          - name: Use Node.js 12.x
            uses: actions/setup-node@v1
            with:
              node-version: 12.x
          - run: npm ci
          - run: npm run build --if-present
          - run: npm start & npx wait-on http://localhost:3000
          - name: Run axe
            run: |
              npm install -g @axe-core/cli
              axe http://localhost:3000 --exit
