
on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'SECURITY.md'
            - 'LICENCE'
            - 'GUIDE.md'
            - 'CONTRIBUTING.md'
            - 'CODE_OF_CONDUCT.md'

jobs:
    compile-themes:
        runs-on: ubuntu-latest
        name: compile themes
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install
  
        - name: Compile Sass
          run: npm run compile:sass
        
        - name: Add and commit changes
          run: |
            git config --global user.name "MarkusJohansen"
            git config --global user.email "markusarj@gmail.com"
            git status
            git add build/*.css
            git commit -m "🤖 Automatic compilation of Sass files"